### ISSUE TITLE
Erroneous Example

### ISSUE THREAD

**Issue by Socjon** [learn-co-curriculum/dsc-1-08-06-introduction-to-sets#1]
> Example: If S is the set of even numbers, set $T = {2, 6, 22}$ is a proper subset of $S$. Formally, you can write this as **$T \subsetneq S$**, or more ambiguously, $T \subset S$.

The notation in the example contradicts the definition of proper subsets. The bold section above should be replaced.

Given: T = {2 , 6, 22}  and S = { all even number}

T is a proper subset of S ,  **$ T \subseteq  S $**

**Comment by LoreDirick** [comment]
@Socjon There was something wrong with the subsets definitions, you're right. Thanks for flagging! It's changed for the new curriculum (repo here: https://github.com/learn-co-curriculum/dsc-intro-to-sets)
