### ISSUE TITLE
Typo? 

### ISSUE THREAD

**Issue by lewi0332** [learn-co-curriculum/dsc-1-08-06-introduction-to-sets#3]
Hi All, 
The line : 'In mathematical terms, the union of  SS  and  TT  is denoted as  S∩TS∩T .",  was very very confusing. 

Until I watched a few other videos to see that the symbol S∩TS∩T means intersection, not union. Maybe I'm wrong here, but it looks like you use the word union for both types of joins (intersection and union). 

Thanks!
Derrick

**Comment by LoreDirick** [comment]
@lewi0332 you're absolutely right, this is confusing. We changed "union" to "intersection" and the change will be pushed out soon. Thank you!
